apiVersion: v1
kind: Secret
metadata:
  name: task-manager-backend-secret
  namespace: task-manager
type: Opaque
stringData:
  MONGO_URI: mongodb://admin:password@mongo-headless.task-manager.svc.cluster.local:27017/taskdb?authSource=admin
  JWT_SECRET: 46408b2c908248345386e133f13d472f73dfe854619c34b3486328fe05174aeb83b4483d366602d3b9bebe5a9fe9ea40988c0173931b665c44f0d1af88201ba7
  ADMIN_INVITE_TOKEN: "4588944"