apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend
  namespace: task-manager
spec:
  type: ClusterIP
  selector:
    app: task-manager-backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http